#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/home/nixen/.local/bin/screen-config &
# bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc query -M | xargs -i bspc monitor {} -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.5
bspc config single_monocle 	  true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding 22

bspc rule -a Gimp state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall pipewire;pipewire &
killall pipewire-pulse;pipewire-pulse &
/home/nixen/.config/polybar/launch.sh &
nitrogen --restore &
picom &
setxkbmap pl &
pgrep bspswallow || bspswallow &
dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus &

xrandr --output HDMI-0 --set TearFree on &
xrandr --output DisplayPort-0 --set TearFree on &
